global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using POC.Core.Bus;
global using MediatR;
global using POC.Core.Commands;
global using POC.Core.Events;
